use challenge_2;

create table CARS (
	MODEL varchar (10),
    BRAND VARCHAR (10),
    CAR_ID varchar (10),
    RELEASE_DATE DATE );

create table BUYERS (
	LAST_NAME varchar (10),
    FIRST_NAME VARCHAR (10),
    EMAIL VARCHAR (30),
    CAR_ID varchar (10),
    MODEL varchar(10),
    PURCHASE_DATE DATE );

create table MODELS (
	CAR_ID varchar (10),
    PRICE VARCHAR (10),
    IN_STOCK varchar (10),
    CAR_TYPE varchar (10),
    RELEASE_DATE DATE );
    
create table MODELS_OPTIONS (
	ID varchar (10),
	FUEL_Y_N varchar (10),
    HYBRID_Y_N VARCHAR (10),
    ELECTRIC_Y_N varchar (10),
    RELEASE_DATE DATE );

create table SALESPERSONS (
	ID varchar (20),
	STAFF_ID varchar (10),
    NAME VARCHAR (20),
    STORE varchar (20) );

INSERT INTO CARS (MODEL,BRAND, CAR_ID, RELEASE_DATE) VALUES ('Model1','PSA', '01', '2000-01-01');
# ...    
INSERT INTO CARS (MODEL,BRAND, CAR_ID, RELEASE_DATE) VALUES ('Model2','GM', '04', '2010-01-01');
INSERT INTO CARS (MODEL,BRAND, CAR_ID, RELEASE_DATE) VALUES ('Model2','GM', '04', '2010-01-01');
# ... AND SO ON



INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('0','00001', 'PETEY CRUISER', 'MADRID');
INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('1','00002', 'ANNA STHESIA', 'BARCELONA');
INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('2','00003', 'PAUL MOLIVE', 'PARIS');
INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('3','00004', 'GAIL FORCEWIND', 'PARIS');
INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('4','00005', 'PAIGE TURNER', 'MIMIA');
INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('5','00006', 'BOB FRAPPLES', 'MEXICO CITY');
INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('6','00007', 'WALTER MELON', 'AMSTERDAM');
INSERT INTO SALESPERSONS (ID, STAFF_ID, NAME, STORE) VALUES ('7','00008', 'SHONDA LEER', 'SAO PAOLO');
 
 
 
INSERT INTO BUYERS (LAST_NAME,FIRST_NAME,CAR_ID,PURCHASE_DATE) VALUES ('AA','MONSIEUR','01','2001-01-01');
INSERT INTO BUYERS (LAST_NAME,FIRST_NAME,CAR_ID,PURCHASE_DATE) VALUES ('BB','MONSIEUR','02','2003-01-01');
INSERT INTO BUYERS (LAST_NAME,FIRST_NAME,CAR_ID,PURCHASE_DATE) VALUES ('CC','MONSIEUR','04','2003-01-01');
INSERT INTO BUYERS (LAST_NAME,FIRST_NAME,CAR_ID,PURCHASE_DATE) VALUES ('DD','MONSIEUR','04','2005-01-01');
INSERT INTO BUYERS (LAST_NAME,FIRST_NAME,CAR_ID,PURCHASE_DATE) VALUES ('EE','MONSIEUR','04','2007-01-01');
INSERT INTO BUYERS (LAST_NAME,FIRST_NAME,CAR_ID,PURCHASE_DATE) VALUES ('FF','MONSIEUR','04','2007-01-01');
INSERT INTO BUYERS (LAST_NAME,FIRST_NAME,CAR_ID,PURCHASE_DATE) VALUES ('GG','MONSIEUR','04','2016-01-01');


INSERT INTO models (car_id, release_date)
  SELECT car_id, C.release_date #colum_name
  FROM CARS C
  where car_id not in (select distinct car_id from models );

INSERT INTO MODELS_OPTIONS (id, release_date)
  SELECT car_id, C.release_date #colum_name
  FROM CARS C
  where car_id not in (select distinct car_id from MODELS_OPTIONS );




select 
last_name,
FIRST_NAME,
b.CAR_ID,
c.Model,
PURCHASE_DATE,
Brand
from BUYERS b
left join cars c on c.car_id = b.car_id
order by PURCHASE_DATE desc;